version: "3.8"

services:
  front:
    build:
      context: ./front  # プロジェクトルートのpath
      dockerfile: ../docker/Dockerfile.front
    ports:
      - "3000:3000"
    depends_on:
      - back
    volumes:
      - ./front:/app
    tty: true

  back:
    build:
      context: ./back
      dockerfile: ../docker/Dockerfile.back
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./back:/app
    tty: true

  core:
    build:
      context: ./core
      dockerfile: ../docker/Dockerfile.core
    ports:
      - "1234:1234"
    depends_on:
      - front
    volumes:
      - ./core:/app
    tty: true

  db:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: develop
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    tty: true

volumes:
  db-data: