tunnel: da38d59a-ee75-48bb-a8ee-e47e10a4c055
credentials-file: /home/nonroot/.cloudflared/da38d59a-ee75-48bb-a8ee-e47e10a4c055.json
protocol: http2

ingress:
  - hostname: mon-gene.wakatsuki.app
    service: http://front:3000
  - hostname: mon-gene-api.wakatsuki.app
    service: http://back:8080
  - hostname: mon-gene-core.wakatsuki.app
    service: http://core:1234
  - service: http_status:404
